---
- name: install application
  hosts: all
  vars:
   - a: tomcat8
     b: present
     c: no
  tasks:
  - name: install s/w apllication
    apt:
            name: "{{a}}"
            state: "{{b}}"
            update_cache: "{{c}}"
...       
